# Generated by Django 6.0 on 2025-12-16 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_released', models.IntegerField()),
                ('release_date', models.DateField()),
                ('expected_arrival_date', models.DateField(blank=True, null=True)),
                ('container_info', models.CharField(blank=True, help_text='Truck/Container No.', max_length=100)),
                ('is_received', models.BooleanField(default=False)),
                ('quotation_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='tracking.quotationitem')),
            ],
        ),
    ]
