# Generated by Django 5.2.3 on 2025-12-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgnoreList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(help_text='Item Code to ignore during API sync', max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='itemmaster',
            name='item_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='itemmaster',
            name='item_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='itemmaster',
            name='item_upvc',
            field=models.CharField(blank=True, help_text='UPC Code', max_length=50, null=True),
        ),
    ]
