# Generated by Django 5.2.3 on 2025-12-18 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_alter_ignorelist_id_alter_itemmaster_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Supplier/Firm name (must match item_firm)', max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, help_text='Supplier logo (optional)', null=True, upload_to='supplier_logos/')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
