# Generated by Django 5.2.3 on 2025-12-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0008_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='manufacturer_name',
            field=models.CharField(blank=True, help_text='Parent company/manufacturer (e.g., Aalberts Group Ltd)', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='supplier_name',
            field=models.CharField(help_text='Brand/Firm name (e.g., PEGLER)', max_length=100),
        ),
    ]
