# Generated by Django 5.2.3 on 2025-12-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0010_manufacturer_remove_quotation_manufacturer_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalPurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(db_index=True, help_text='Brand/Sheet Name (e.g., HEPWORTH)', max_length=100)),
                ('item_code', models.CharField(max_length=50)),
                ('upc_code', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True)),
                ('current_stock_ras', models.IntegerField(default=0)),
                ('current_stock_dip', models.IntegerField(default=0)),
                ('sold_qty_2024', models.IntegerField(default=0)),
                ('contg', models.IntegerField(default=0)),
                ('trdg', models.IntegerField(default=0)),
                ('stores', models.IntegerField(default=0)),
                ('total_sold_qty_2025', models.IntegerField(default=0)),
                ('avg_15day_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('stock_sufficiency_months', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('lpo_given', models.IntegerField(default=0)),
                ('open_so_qty', models.IntegerField(default=0)),
                ('stock_reqt_calcn', models.IntegerField(default=0)),
                ('stock_requirement', models.IntegerField(default=0)),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('ho_per_lpo_qty', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('stock_reqt_ras_stores', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Local Purchase Item',
                'verbose_name_plural': 'Local Purchase Items',
                'ordering': ['brand', 'item_code'],
            },
        ),
    ]
