# Generated by Django 5.2.3 on 2025-12-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0011_localpurchaseitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localpurchaseitem',
            name='stock_sufficiency_months',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10),
        ),
    ]
