# Generated by Django 5.2.3 on 2026-01-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0012_alter_localpurchaseitem_stock_sufficiency_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('AED', 'AED'), ('GBP', 'GBP')], default='USD', help_text='Currency for this quotation', max_length=3),
        ),
    ]
