# Generated by Django 5.2.3 on 2026-01-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0013_add_currency_to_quotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='supplier_name',
            field=models.TextField(help_text='Brand/Firm names (comma-separated, e.g., PEGLER, PEGLER-CHILLED)'),
        ),
    ]
