# Generated by Django 5.2.3 on 2026-01-31 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0014_change_supplier_name_to_textfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmaster',
            name='total_qty',
            field=models.IntegerField(default=0, help_text='Total Sold Quantity'),
        ),
    ]
