# Generated by Django 5.2.3 on 2026-01-31 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0015_add_total_qty_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmaster',
            name='reorder_qty',
            field=models.IntegerField(blank=True, default=0, help_text='Quantity to order next', null=True),
        ),
    ]
